<?php

namespace Magan\FilamentBlog;

use Artesaos\SEOTools\Providers\SEOToolsServiceProvider;
use Magan\FilamentBlog\Components\Layout;
use Magan\FilamentBlog\Components\RecentPost;
use Spatie\LaravelPackageTools\Commands\InstallCommand;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class FilamentBlogServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package->name('filament-blog')
            ->hasConfigFile(['filamentblog'])
            ->hasMigration('create_blog_tables')
            ->hasViewComponents('blog', Layout::class, RecentPost::class)
            ->hasViews('filament-blog')
            ->hasRoute('web')
            ->hasInstallCommand(function (InstallCommand $installCommand) {
                $installCommand
                    ->startWith(function (InstallCommand $command) {
                        $command->info('Hello, and welcome to my great new package!');
                    })
                    ->publishConfigFile()
                    ->publishMigrations()
                    ->endWith(function (InstallCommand $installCommand) {
                        $installCommand->info("Get ready to breathe easy! Our package has just saved you from a day's worth of headaches and hassle.");
                    });
            });
    }

    public function register()
    {
        $this->app->register(SEOToolsServiceProvider::class);

        return parent::register(); // TODO: Change the autogenerated stub
    }
}
